### ISSUE TITLE
Upload 0.2.4 to clojars

### ISSUE THREAD

**Issue by vitalyper** [tobias/dynapath#6]
When you have a chance could you please upload 0.2.4 to clojars? 
Our company blocks Maven Central but proxies Clojars. Your library is a dependency of cider/cider-nrepl and I can't use emacs+cider ATM.

```
Retrieving cider/cider-nrepl/0.15.0-SNAPSHOT/cider-nrepl-0.15.0-20161014.121923-2.jar from clojars
...
Could not find artifact org.tcrawley:dynapath:jar:0.2.4 in clojars (https://clojars.org/repo/)
```

**Comment by tobias** [comment]
I'm sorry, but I won't be uploading any more dynapath releases to clojars. Clojars is about to disable uploads of anything that is also on central anyway. See https://github.com/clojars/clojars-web/issues/468 for more details.
