### ISSUE TITLE
Updating Changelog.md

### ISSUE THREAD

**Issue by camsaul** [tobias/dynapath#9]
Hi, great library. I was wondering whether you could update the Changelog or otherwise provide some sort of release notes for this version? I just noticed there was a huge version bump from 0.2.5 to 1.0.0 but am struggling to figure out what's new and whether there are breaking changes.

**Comment by tobias** [comment]
Thanks for the prod - I touch this project so rarely that I forgot it had a Changelog. I've updated it; feel free to ping me if you have any questions or issues.
